"""
Supabase persistence client for the content storyboard ledger.

PostgreSQL DDL:

CREATE TABLE IF NOT EXISTS content_storyboards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    topic_headline TEXT NOT NULL,
    sentiment_score FLOAT NOT NULL,
    market_bias VARCHAR(50) NOT NULL,
    video_title TEXT NOT NULL,
    audio_script TEXT NOT NULL,
    visual_prompts TEXT NOT NULL,
    media_audio_url TEXT DEFAULT NULL,
    media_video_url TEXT DEFAULT NULL,
    status VARCHAR(50) DEFAULT 'Pending Video Production'
);
"""

from __future__ import annotations

import asyncio
import logging
from functools import lru_cache
from typing import Any

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict
from supabase import Client, create_client


logger = logging.getLogger(__name__)


class SupabaseSettings(BaseSettings):
    """Runtime configuration for the Supabase persistence client."""

    supabase_url: str = Field(alias="SUPABASE_URL")
    supabase_key: str = Field(alias="SUPABASE_KEY")

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )


@lru_cache(maxsize=1)
def get_supabase_client() -> Client:
    """Create and cache a native Supabase SDK client."""
    settings = SupabaseSettings()
    return create_client(settings.supabase_url, settings.supabase_key)


def _response_data(response: Any) -> Any:
    data = getattr(response, "data", None)
    if data is None:
        raise RuntimeError("Supabase response did not include a data payload.")
    return data


async def save_agent_storyboard(payload: dict[str, Any]) -> dict[str, Any]:
    """
    Insert a structured storyboard payload into the content_storyboards ledger.

    Returns the generated row dictionary emitted by Supabase.
    """
    try:
        logger.info("Saving agent storyboard to Supabase ledger.")
        client = get_supabase_client()
        response = await asyncio.to_thread(
            lambda: client.table("content_storyboards").insert(payload).execute()
        )
        data = _response_data(response)

        if not isinstance(data, list) or not data:
            raise RuntimeError("Supabase insert returned no generated row data.")

        row = data[0]
        if not isinstance(row, dict):
            raise TypeError("Supabase insert returned an unexpected row payload.")

        logger.info("Saved agent storyboard row with id=%s.", row.get("id"))
        return row
    except Exception:
        logger.exception("Failed to save agent storyboard to Supabase.")
        raise


async def get_active_pipeline_history() -> list[dict[str, Any]]:
    """
    Fetch the latest active storyboard pipeline records in reverse chronological order.
    """
    try:
        logger.info("Fetching active pipeline history from Supabase ledger.")
        client = get_supabase_client()
        response = await asyncio.to_thread(
            lambda: (
                client.table("content_storyboards")
                .select("*")
                .order("created_at", desc=True)
                .limit(25)
                .execute()
            )
        )
        data = _response_data(response)

        if not isinstance(data, list):
            raise TypeError("Supabase history query returned an unexpected payload.")

        history = [item for item in data if isinstance(item, dict)]
        logger.info("Fetched %d storyboard history rows.", len(history))
        return history
    except Exception:
        logger.exception("Failed to fetch active pipeline history from Supabase.")
        raise
